### ISSUE TITLE
Why does saco exists?

### ISSUE THREAD

**Issue by sebasgarcep** [bertolo1988/saco#5]
I really don't mean to be rude but if you are making a project you have to point out why it is necessary. Why can't you solve this problem with boilerplate code or how it is different from other similar projects?

**Comment by bertolo1988** [comment]
Hello @sebasgarcep.

I needed an http-server for my front-end single page web app. I had to install it on a linux dropplet with 512mb of ram and the nodejs options i found were:

 1. [http-server](https://www.npmjs.com/package/http-server)
 2. nodemon, live-server, lite-server, ng serve
 3. write my own with express

### 1

Every folder would be a new route, i needed all requests redirected to a single file. I tried to search for the flag/option or a way to do it and eventually quit.

### 2

Live-reloading, open web browser on launch...etc those are features for development servers. I don't want none of that.


### 3

This was my only option considering that i needed a few features such as: start/stop, console-logging, https, minification, logging...etc


By creating an open source repository i get:

* to help someone facing a similar problem with similar options
* hopefully get contribution, suggestions, supervision which in the end will ensure quality and best practices
* i can just include a `saco`, a `start.js` and a npm script in my front end app development repository and i got it ready for production
